version: "3.9"

services:


  sodor24-database-service:
    image: mysql:8.4.6
    container_name: sodor24-db-service
    restart: unless-stopped

    environment:
      TZ: Asia/Tehran
      MYSQL_ROOT_PASSWORD: zamanian1379
      MYSQL_DATABASE: sodor24db
      MYSQL_USER: admin
      MYSQL_PASSWORD: zamanian1379

    ports:
      - "3307:3306"

    volumes:
      - sodor24-db-volume:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-pzamanian1379"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s

    networks:
      - app-network


  rabbitmq-service:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-service
    restart: unless-stopped

    environment:
      TZ: Asia/Tehran
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: zamanian1379

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

    networks:
      - app-network



  redis-service:
    image: redis:7-alpine
    container_name: redis-service
    restart: unless-stopped

    command: redis-server --appendonly yes --requirepass zamanian1379

    ports:
      - "6379:6379"

    volumes:
      - redis-volume:/data

    healthcheck:
      test: ["CMD", "redis-cli", "-a", "zamanian1379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s

    networks:
      - app-network


  sodor24-server:
    image: alizamanian/sodor24-server:latest
    container_name: sodor24-server

    restart: unless-stopped
    pull_policy: always

    ports:
      - "8181:8181"

    environment:
      TZ: Asia/Tehran

      SERVER_PORT: 8181
      APP_ENV: dev
      APP_CLIENT_HOST: http://0.0.0.0:3000
      CURRENCY: IRT

      SPRING_DATASOURCE_URL: jdbc:mysql://sodor24-database-service:3306/sodor24db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tehran
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: zamanian1379

      SPRING_RABBITMQ_HOST: rabbitmq-service
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: zamanian1379

      SPRING_DATA_CATCHE_TYPE: redis
      SPRING_DATA_REDIS_HOST: redis-service
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: zamanian1379

    depends_on:
      sodor24-database-service:
        condition: service_healthy

      rabbitmq-service:
        condition: service_healthy

      redis-service:
        condition: service_healthy

    networks:
      - app-network



  wallet-service:
    image: alizamanian/wallet-service:latest
    container_name: wallet-service

    restart: unless-stopped
    pull_policy: always

    ports:
      - "8489:8489"

    environment:
      TZ: Asia/Tehran

      SERVER_PORT: 8489

      DB_RESOURCE: jdbc:mysql://sodor24-database-service:3306/walletdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tehran
      DB_USER: admin
      DB_PASSWORD: zamanian1379

      SPRING_RABBITMQ_HOST: rabbitmq-service
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: zamanian1379

      ZARINPAL_ENV: dev
      ZARINPAL_MERCHANT_ID: d8234a3a-dbcf-4f30-ab52-b195b0f0f1a3

    depends_on:
      sodor24-database-service:
        condition: service_healthy

      rabbitmq-service:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8489/actuator/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s

    networks:
      - app-network



  signature-service:
    image: alizamanian/signature-service:latest
    container_name: signature-service
    restart: always
    pull_policy: always
    ports:
      - "8585:8585"
    environment:
      TZ: Asia/Tehran
      SERVER_PORT: 8585
      SPRING_RABBITMQ_HOST: rabbitmq-service
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: zamanian1379

    volumes:
      - signature_storage:/app/storage

    depends_on:
      sodor24-server:
        condition: service_started

    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8585/actuator/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s

    networks:
      - app-network

  sodor24-client:
    image: alizamanian/sodor24-client:latest
    build:
      context: ./
      args:
        NEXT_PUBLIC_SERVER_HOST: http://sodor24-server:8181

    ports:
      - "3000:3000"
    depends_on:
      sodor24-server:
        condition: service_started
    networks:
      - app-network



# ======================================
# Volumes
# ======================================
volumes:
  sodor24-db-volume:
  rabbitmq-volume:
  redis-volume:
  signature_storage:

# ======================================
# Networks
# ======================================
networks:
  app-network:
    name: app-network
    driver: bridge