# ==================== Spring config ==================== #
spring.application.name=sodor24-server
boycott.countries=
#boycott.countries=United States
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# ==================== Jwt config ==================== #
jwt.access-token-secret=0123456789abcdef0123456789abcdef
jwt.refresh-token-secret=0123456789abcdef0195995d93456789abcdef
jwt.access-token.expired-time.minutes=20
jwt.refresh-token.expired-time.day=7

# ==================== Catching config ==================== #
spring.cache.type=${SPRING_REDIS_HOST}
spring.redis.host=localhost
spring.redis.port=6379



# ==================== Wallet config ==================== #
application.wallet-service.currency=IRT

application.wallet-service.payments.zarinpal.env=dev
application.wallet-service.payments.zarinpal.name=zarinpal
application.wallet-service.payments.zarinpal.merchant_id=d8234a3a-dbcf-4f30-ab52-b195b0f0f1a3

application.wallet-service.rabbitmq.queue.list-wallet=wallet.list.queue
application.wallet-service.rabbitmq.queue.create-wallet=wallet.create.queue
application.wallet-service.rabbitmq.queue.get-wallet=wallet.get.queue
application.wallet-service.rabbitmq.queue.active-wallet=wallet.active.queue
application.wallet-service.rabbitmq.queue.delete-wallet=wallet.delete.queue
application.wallet-service.rabbitmq.queue.update-sub-wallet=wallet.update.sub.queue
application.wallet-service.rabbitmq.queue.payment-request-wallet=wallet.request.payment.queue
application.wallet-service.rabbitmq.queue.payment-verifier-wallet=wallet.verifier.payment.queue

application.wallet-service.rabbitmq.exchange=wallet.exchange
application.wallet-service.rabbitmq.routing.list-wallet=wallet.list.routing-key
application.wallet-service.rabbitmq.routing.create-wallet=wallet.create.routing-key
application.wallet-service.rabbitmq.routing.get-wallet=wallet.get.routing-key
application.wallet-service.rabbitmq.routing.active-wallet=wallet.active.routing-key
application.wallet-service.rabbitmq.routing.delete-wallet=wallet.delete.routing-key
application.wallet-service.rabbitmq.routing.update-sub-wallet=wallet.update.sub.routing-key
application.wallet-service.rabbitmq.routing.payment-request-wallet=wallet.request.payment.routing-key
application.wallet-service.rabbitmq.routing.payment-verifier-wallet=wallet.verifier.payment.routing-key