# ==================== Jpa config Mysql ==================== #
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/sodor24db?createDatabaseIfNotExist=true}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

# ==================== Spring config ==================== #
spring.application.name=sodor24-server
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
boycott.countries=
#boycott.countries=United States
server.port=${SERVER_PORT:8181}
app.client.host=${APP_CLIENT_HOST:http://192.168.1.7:3000}
app.env=${APP_ENV:dev}
application.wallet-service.currency=${CURRENCY:IRT}

# ==================== Jwt config ==================== #
jwt.access-token-secret=0123456789abcdef0123456789abcdef
jwt.refresh-token-secret=0123456789abcdef0195995d93456789abcdef
jwt.access-token.expired-time.minutes=20
jwt.refresh-token.expired-time.day=7

# ==================== Catching config ==================== #
spring.cache.type=${SPRING_DATA_CATCHE_TYPE:redis}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:guest}

# ==================== RabbitMQ config ==================== #
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}

# ==================== Wallet config ==================== #
application.wallet-service.rabbitmq.exchange=wallet.exchange
application.wallet-service.rabbitmq.routing.list-wallet=wallet.list.routing-key
application.wallet-service.rabbitmq.routing.create-wallet=wallet.create.routing-key
application.wallet-service.rabbitmq.routing.get-wallet=wallet.get.routing-key
application.wallet-service.rabbitmq.routing.active-wallet=wallet.active.routing-key
application.wallet-service.rabbitmq.routing.delete-wallet=wallet.delete.routing-key
application.wallet-service.rabbitmq.routing.update-sub-wallet=wallet.update.sub.routing-key
application.wallet-service.rabbitmq.routing.payment-request-wallet=wallet.request.payment.routing-key
application.wallet-service.rabbitmq.routing.payment-verifier-wallet=wallet.verifier.payment.routing-key
application.wallet-service.rabbitmq.routing.transaction-list=transaction.list.routing-key
application.wallet-service.rabbitmq.routing.get-transaction-by-slug=get.transaction.by.slug.routing-key
application.wallet-service.rabbitmq.routing.get-transaction-in-date=get.transaction.in.date.routing-key
application.wallet-service.rabbitmq.routing.delete-transaction-by-slug=delete.transaction.by.slug.routing-key

# ==================== Signature service config ==================== #
application.signature-service.rabbitmq.exchange=signature-service-exchange
application.signature-service.rabbitmq.routing-keys.signature=signature-routing-key
application.signature-service.rabbitmq.routing-keys.contract=contract-routing-key
application.signature-service.rabbitmq.routing-keys.download=download-routing-key

# ==================== sms config ==================== #
niazpardaz.sms.api-key=lLr5LXq8Gxo9tFk1GHU9vQceBbzIADyfRTaJGOeSy5vFGVnLQiezcdLT8ysVDdvtYcIO6HRLrwDap2s0
niazpardaz.sms.connect-timeout=10000
niazpardaz.sms.read-timeout=30000
niazpardaz.sender.number=10009611

# ==================== Keycloak config ==================== #
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/myrealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/myrealm/protocol/openid-connect/certs
application.keycloak.client.id=app-cli