CREATE DATABASE IF NOT EXISTS sodor24db;
CREATE DATABASE IF NOT EXISTS walletdb;

GRANT ALL PRIVILEGES ON sodor24db.* TO 'admin'@'%';
GRANT ALL PRIVILEGES ON walletdb.* TO 'admin'@'%';

FLUSH PRIVILEGES;