version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  signature-service:
#    image: signature-service:v1.0.0
    image: alizamanian/signature-service:latest
    container_name: signature-service
    ports:
      - "8585:8585"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      SERVER_PORT: 8585
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    restart: unless-stopped

volumes:
  rabbitmq:
