version: "3.8"

services:

  wallet-service:
    image: alizamanian/wallet-service:v1.0.0
    container_name: wallet-service
    ports:
      - "8489:8489"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: wallet_service_db
      DB_USER: root
      DB_PASSWORD: 1234
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  new-service:
    build: .
    container_name: new-service
    ports:
      - "8490:8490"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: new_service_db
      DB_USER: root
      DB_PASSWORD: 1234
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: shared-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shared-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  rabbitmq_data: